name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy to Server via SCP & SSH
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          scp: |
            ./frontend/dist => /root/frontend/
          last_ssh: |
            nginx -t && systemctl reload nginx
